language: c
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - opam
      - aspcud
env:
  matrix:
    - MODE=build COQ_VERSION=8.6.1
    - MODE=build COQ_VERSION=8.7.1
    - MODE=checker COQ_VERSION=8.7.1
script: bash -ex .travis-ci.sh
sudo: false
notifications:
  email: false
